# Generated by Django 5.2.4 on 2025-07-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fer_auth', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE fer_auth_userprofile ALTER COLUMN created_at DROP NOT NULL;'),
    ]
