# Generated by Django 5.2.4 on 2025-07-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_auth', '0002_make_userprofile_created_at_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
