# Generated by Django 5.2.4 on 2025-07-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fer_auth', '0005_transfer_tokens_to_profiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
