# Generated by Django 5.2.4 on 2025-07-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fer_auth', '0006_remove_token_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_backup_codes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_temp_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
